In [1]:
import pandas as pd
import numpy as np

In [2]:
filepath = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DA0101EN-Coursera/laptop_pricing_dataset_base.csv"
df = pd.read_csv(filepath, header=None)

In [3]:
df.head(5)

     0   1          2   3   4   5       6    7   8    9     10    11
0  Acer   4  IPS Panel   2   1   5   35.56  1.6   8  256   1.6   978
1  Dell   3    Full HD   1   1   3  39.624  2.0   4  256   2.2   634
2  Dell   3    Full HD   1   1   7  39.624  2.7   8  256   2.2   946
3  Dell   4  IPS Panel   2   1   5  33.782  1.6   8  128  1.22  1244
4    HP   4    Full HD   2   1   7  39.624  1.8   8  256  1.91   837

In [4]:
headers = ["Manufacturer", "Category", "Screen", "GPU", "OS", "CPU_core", "Screen_Size_inch", "CPU_frequency", "RAM_GB", "Storage_GB_SSD", "Weight_kg", "Price"]

In [7]:
df.columns = headers
print(df.columns)

Index(['Manufacturer', 'Category', 'Screen', 'GPU', 'OS', 'CPU_core',
       'Screen_Size_inch', 'CPU_frequency', 'RAM_GB', 'Storage_GB_SSD',
       'Weight_kg', 'Price'],
      dtype='object')

In [8]:
df.head(5)

,Manufacturer,Category,Screen,GPU,OS,CPU_core,Screen_Size_inch,CPU_frequency,RAM_GB,Storage_GB_SSD,Weight_kg,Price
0,Acer,4,IPS Panel,2,1,5,35.56,1.6,8,256,1.6,978
1,Dell,3,Full HD,1,1,3,39.624,2.0,4,256,2.2,634
2,Dell,3,Full HD,1,1,7,39.624,2.7,8,256,2.2,946
3,Dell,4,IPS Panel,2,1,5,33.782,1.6,8,128,1.22,1244
4,HP,4,Full HD,2,1,7,39.624,1.8,8,256,1.91,837

In [9]:
df.replace('?', np.nan)

,Manufacturer,Category,Screen,GPU,OS,CPU_core,Screen_Size_inch,CPU_frequency,RAM_GB,Storage_GB_SSD,Weight_kg,Price
0,Acer,4,IPS Panel,2,1,5,35.56,1.6,8,256,1.6,978
1,Dell,3,Full HD,1,1,3,39.624,2.0,4,256,2.2,634
2,Dell,3,Full HD,1,1,7,39.624,2.7,8,256,2.2,946
3,Dell,4,IPS Panel,2,1,5,33.782,1.6,8,128,1.22,1244
4,HP,4,Full HD,2,1,7,39.624,1.8,8,256,1.91,837
...,...,...,...,...,...,...,...,...,...,...,...,...
233,Lenovo,4,IPS Panel,2,1,7,35.56,2.6,8,256,1.7,1891
234,Toshiba,3,Full HD,2,1,5,33.782,2.4,8,256,1.2,1950
235,Lenovo,4,IPS Panel,2,1,5,30.48,2.6,8,256,1.36,2236
236,Lenovo,3,Full HD,3,1,5,39.624,2.5,6,256,2.4,883
237,Toshiba,3,Full HD,2,1,5,35.56,2.3,8,256,1.95,1499

In [14]:
df.dtypes

Manufacturer         object
Category              int64
Screen               object
GPU                   int64
OS                    int64
CPU_core              int64
Screen_Size_inch     object
CPU_frequency       float64
RAM_GB                int64
Storage_GB_SSD        int64
Weight_kg            object
Price                 int64
dtype: object

In [18]:
# statistical description
print(df.describe(include = 'all'))

       Manufacturer    Category   Screen         GPU          OS    CPU_core  \
count           238  238.000000      238  238.000000  238.000000  238.000000
unique           11         NaN        2         NaN         NaN         NaN
top            Dell         NaN  Full HD         NaN         NaN         NaN
freq             71         NaN      161         NaN         NaN         NaN
mean            NaN    3.205882      NaN    2.151261    1.058824    5.630252
std             NaN    0.776533      NaN    0.638282    0.235790    1.241787
min             NaN    1.000000      NaN    1.000000    1.000000    3.000000
25%             NaN    3.000000      NaN    2.000000    1.000000    5.000000
50%             NaN    3.000000      NaN    2.000000    1.000000    5.000000
75%             NaN    4.000000      NaN    3.000000    1.000000    7.000000
max             NaN    5.000000      NaN    3.000000    2.000000    7.000000

       Screen_Size_inch  CPU_frequency      RAM_GB  Storage_GB_SSD Weight_kg  \
count               238     238.000000  238.000000      238.000000       238
unique               10            NaN         NaN             NaN        78
top              39.624            NaN         NaN             NaN       2.2
freq                 89            NaN         NaN             NaN        21
mean                NaN       2.360084    7.882353      245.781513       NaN
std                 NaN       0.411393    2.482603       34.765316       NaN
min                 NaN       1.200000    4.000000      128.000000       NaN
25%                 NaN       2.000000    8.000000      256.000000       NaN
50%                 NaN       2.500000    8.000000      256.000000       NaN
75%                 NaN       2.700000    8.000000      256.000000       NaN
max                 NaN       2.900000   16.000000      256.000000       NaN

              Price
count    238.000000
unique          NaN
top             NaN
freq            NaN
mean    1462.344538
std      574.607699
min      527.000000
25%     1066.500000
50%     1333.000000
75%     1777.000000
max     3810.000000

In [19]:
# summary
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 238 entries, 0 to 237
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Manufacturer      238 non-null    object
 1   Category          238 non-null    int64
 2   Screen            238 non-null    object
 3   GPU               238 non-null    int64
 4   OS                238 non-null    int64
 5   CPU_core          238 non-null    int64
 6   Screen_Size_inch  238 non-null    object
 7   CPU_frequency     238 non-null    float64
 8   RAM_GB            238 non-null    int64
 9   Storage_GB_SSD    238 non-null    int64
 10  Weight_kg         238 non-null    object
 11  Price             238 non-null    int64
dtypes: float64(1), int64(7), object(4)
memory usage: 22.4+ KB