In [8]:
import pandas as pd
import matplotlib.pylab as plt
import numpy as np

In [2]:
df = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DA0101EN-SkillsNetwork/labs/Data%20files/auto.csv")

In [3]:
df.head()

,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
1,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
2,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
3,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
4,2,?,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250

In [4]:
headers = ["symboling","normalized-losses","make","fuel-type","aspiration", "num-of-doors","body-style",
         "drive-wheels","engine-location","wheel-base", "length","width","height","curb-weight","engine-type",
         "num-of-cylinders", "engine-size","fuel-system","bore","stroke","compression-ratio","horsepower",
         "peak-rpm","city-mpg","highway-mpg","price"]

In [5]:
df.columns = headers

In [6]:
df.head(2)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
1,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500

## Identify missing values
### convert "?" to NaN

In [9]:
df.replace("?", np.nan, inplace = True)

Evaluate missing vales

.isnull()
.notnull()

In [10]:
missing_data = df.isnull()
missing_data.head(4)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

count missing values in each column

In [11]:
for column in missing_data.columns.values.tolist():
    print(column)
    print(missing_data[column].value_counts)
    print("")

symboling
<bound method IndexOpsMixin.value_counts of 0      False
1      False
2      False
3      False
4      False
       ...
199    False
200    False
201    False
202    False
203    False
Name: symboling, Length: 204, dtype: bool>

normalized-losses
<bound method IndexOpsMixin.value_counts of 0       True
1       True
2      False
3      False
4       True
       ...
199    False
200    False
201    False
202    False
203    False
Name: normalized-losses, Length: 204, dtype: bool>

make
<bound method IndexOpsMixin.value_counts of 0      False
1      False
2      False
3      False
4      False
       ...
199    False
200    False
201    False
202    False
203    False
Name: make, Length: 204, dtype: bool>

fuel-type
<bound method IndexOpsMixin.value_counts of 0      False
1      False
2      False
3      False
4      False
       ...
199    False
200    False
201    False
202    False
203    False
Name: fuel-type, Length: 204, dtype: bool>

aspiration
<bound method IndexOpsMixin.value_counts of 0      False
1      False
2      False
3      False
4      False
       ...
199    False
200    False
201    False
202    False
203    False
Name: aspiration, Length: 204, dtype: bool>

num-of-doors
<bound method IndexOpsMixin.value_counts of 0      False
1      False
2      False
3      False
4      False
       ...
199    False
200    False
201    False
202    False
203    False
Name: num-of-doors, Length: 204, dtype: bool>

body-style
<bound method IndexOpsMixin.value_counts of 0      False
1      False
2      False
3      False
4      False
       ...
199    False
200    False
201    False
202    False
203    False
Name: body-style, Length: 204, dtype: bool>

drive-wheels
<bound method IndexOpsMixin.value_counts of 0      False
1      False
2      False
3      False
4      False
       ...
199    False
200    False
201    False
202    False
203    False
Name: drive-wheels, Length: 204, dtype: bool>

engine-location
<bound method IndexOpsMixin.value_counts of 0      False
1      False
2      False
3      False
4      False
       ...
199    False
200    False
201    False
202    False
203    False
Name: engine-location, Length: 204, dtype: bool>

wheel-base
<bound method IndexOpsMixin.value_counts of 0      False
1      False
2      False
3      False
4      False
       ...
199    False
200    False
201    False
202    False
203    False
Name: wheel-base, Length: 204, dtype: bool>

length
<bound method IndexOpsMixin.value_counts of 0      False
1      False
2      False
3      False
4      False
       ...
199    False
200    False
201    False
202    False
203    False
Name: length, Length: 204, dtype: bool>

width
<bound method IndexOpsMixin.value_counts of 0      False
1      False
2      False
3      False
4      False
       ...
199    False
200    False
201    False
202    False
203    False
Name: width, Length: 204, dtype: bool>

height
<bound method IndexOpsMixin.value_counts of 0      False
1      False
2      False
3      False
4      False
       ...
199    False
200    False
201    False
202    False
203    False
Name: height, Length: 204, dtype: bool>

curb-weight
<bound method IndexOpsMixin.value_counts of 0      False
1      False
2      False
3      False
4      False
       ...
199    False
200    False
201    False
202    False
203    False
Name: curb-weight, Length: 204, dtype: bool>

engine-type
<bound method IndexOpsMixin.value_counts of 0      False
1      False
2      False
3      False
4      False
       ...
199    False
200    False
201    False
202    False
203    False
Name: engine-type, Length: 204, dtype: bool>

num-of-cylinders
<bound method IndexOpsMixin.value_counts of 0      False
1      False
2      False
3      False
4      False
       ...
199    False
200    False
201    False
202    False
203    False
Name: num-of-cylinders, Length: 204, dtype: bool>

engine-size
<bound method IndexOpsMixin.value_counts of 0      False
1      False
2      False
3      False
4      False
       ...
199    False
200    False
201    False
202    False
203    False
Name: engine-size, Length: 204, dtype: bool>

fuel-system
<bound method IndexOpsMixin.value_counts of 0      False
1      False
2      False
3      False
4      False
       ...
199    False
200    False
201    False
202    False
203    False
Name: fuel-system, Length: 204, dtype: bool>

bore
<bound method IndexOpsMixin.value_counts of 0      False
1      False
2      False
3      False
4      False
       ...
199    False
200    False
201    False
202    False
203    False
Name: bore, Length: 204, dtype: bool>

stroke
<bound method IndexOpsMixin.value_counts of 0      False
1      False
2      False
3      False
4      False
       ...
199    False
200    False
201    False
202    False
203    False
Name: stroke, Length: 204, dtype: bool>

compression-ratio
<bound method IndexOpsMixin.value_counts of 0      False
1      False
2      False
3      False
4      False
       ...
199    False
200    False
201    False
202    False
203    False
Name: compression-ratio, Length: 204, dtype: bool>

horsepower
<bound method IndexOpsMixin.value_counts of 0      False
1      False
2      False
3      False
4      False
       ...
199    False
200    False
201    False
202    False
203    False
Name: horsepower, Length: 204, dtype: bool>

peak-rpm
<bound method IndexOpsMixin.value_counts of 0      False
1      False
2      False
3      False
4      False
       ...
199    False
200    False
201    False
202    False
203    False
Name: peak-rpm, Length: 204, dtype: bool>

city-mpg
<bound method IndexOpsMixin.value_counts of 0      False
1      False
2      False
3      False
4      False
       ...
199    False
200    False
201    False
202    False
203    False
Name: city-mpg, Length: 204, dtype: bool>

highway-mpg
<bound method IndexOpsMixin.value_counts of 0      False
1      False
2      False
3      False
4      False
       ...
199    False
200    False
201    False
202    False
203    False
Name: highway-mpg, Length: 204, dtype: bool>

price
<bound method IndexOpsMixin.value_counts of 0      False
1      False
2      False
3      False
4      False
       ...
199    False
200    False
201    False
202    False
203    False
Name: price, Length: 204, dtype: bool>

## handling missing values
### Drop Data
#### drop whole row
#### drop whole column
### Replace Data
### replace by mean
### replace by frequency
### replace based on functions

In [12]:
# calculate mean for normalized losses
avg_norm_loss = df["normalized-losses"].astype("float").mean(axis = 0)
print("Average of normalized losses:", avg_norm_loss)

Average of normalized losses: 122.0

In [13]:
df["normalized-losses"].replace(np.nan, avg_norm_loss, inplace = True)

In [14]:
avg_bore = df["bore"].astype("float").mean(axis = 0)
print("average of bore:", avg_bore)

average of bore: 3.3290499999999996

In [15]:
df["bore"].replace(np.nan, avg_bore, inplace = True)

In [16]:
avg_stroke = df["stroke"].astype("float").mean(axis = 0)
df["stroke"].replace(np.nan, avg_bore, inplace = True)

In [18]:
df["num-of-doors"].value_counts()

num-of-doors
four    114
two      88
Name: count, dtype: int64

In [21]:
df['num-of-doors'].value_counts().idxmax()

'four'